[package]
name = "fds-input-parser"
version = "0.1.3"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
namelist = {git = "https://github.com/JakeOShannessy/namelist-rs.git"}
