[package]
name = "fds-input-parser"
version = "0.1.2"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
namelist = {git = "ssh://git@github.com/JakeOShannessy/namelist-rs.git"}
